### ISSUE TITLE
[Question] Steps to deploy this website on Heroku?

### ISSUE THREAD

**Issue by CatchMeIfYouCan4401** [jcserv/portfolio#25]
I really loved the website but I am desperate to know whether I can deploy it from heroku or not. Can you please provide steps on how can one deploy it on heroku?

**Comment by jcserv** [comment]
Hey there, glad to hear you liked the site!
I followed this tutorial: https://www.youtube.com/watch?v=71wSzpLyW9k
when deploying my site.

I can create a set of instructions hopefully next week assuming school/work doesn't get too busy!
